# https://taskfile.dev

version: '3'

dotenv: ['.env']

tasks:
  up: go run cmd/sso/main.go --config config/local.yml

  db-migrate:
    desc: Migrate database
    cmd: go run github.com/steebchen/prisma-client-go migrate dev {{.CLI_ARGS}}

  prepare-test-data:
    desc: 'Prepare test data: add test App with app_id: 1'
    cmd: go run cmd/migrate-data/main.go

  test:
    desc: Run tests
    cmd: go test -v ./tests

  clean-cache-tests:
    aliases: [clean]
    desc: Clean test cache
    cmd: go clean -testcache

  lint:
    desc: Lint code
    cmd: golangci-lint run
