# https://taskfile.dev

version: '3'

dotenv: ['.env']

tasks:
  up: go run cmd/sso/main.go --config config/local.yml

  db-migrate:
    desc: Migrate database
    cmd: go run github.com/steebchen/prisma-client-go migrate dev {{.CLI_ARGS}}
